// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbihSCMvrNCEt61NnFNKcoo2TCTfNf9g',
    appId: '1:507301477978:web:253c031da4783aa250a263',
    messagingSenderId: '507301477978',
    projectId: 'unimatch-63d64',
    authDomain: 'unimatch-63d64.firebaseapp.com',
    storageBucket: 'unimatch-63d64.appspot.com',
    measurementId: 'G-D8LLPX631E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmM8RDJDYLBtEFQfjnGnmwG1cB3DhVcM',
    appId: '1:507301477978:android:542c9ebd510f43ee50a263',
    messagingSenderId: '507301477978',
    projectId: 'unimatch-63d64',
    storageBucket: 'unimatch-63d64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjLWGqbLSJyjttZyCAjRuGBcGH6aSSoas',
    appId: '1:507301477978:ios:470c8321e4ac18a150a263',
    messagingSenderId: '507301477978',
    projectId: 'unimatch-63d64',
    storageBucket: 'unimatch-63d64.appspot.com',
    iosClientId: '507301477978-npjkgp9glm7k49lklun3qaraqufunsi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjLWGqbLSJyjttZyCAjRuGBcGH6aSSoas',
    appId: '1:507301477978:ios:470c8321e4ac18a150a263',
    messagingSenderId: '507301477978',
    projectId: 'unimatch-63d64',
    storageBucket: 'unimatch-63d64.appspot.com',
    iosClientId: '507301477978-npjkgp9glm7k49lklun3qaraqufunsi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimatch',
  );
}
